# Generated by Django 5.2.4 on 2025-08-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_postimage_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='allow_comments',
        ),
        migrations.AddField(
            model_name='post',
            name='approved_post',
            field=models.BooleanField(default=False),
        ),
    ]
